=== firebearstudio/importexportfree/etc/source_types.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="type" type="typeDeclaration" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="typeDeclaration">
        <xs:sequence>
            <xs:element name="field" type="fieldDeclaration" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="label" type="xs:string" use="required"/>
        <xs:attribute name="modelInstance" type="modelName" use="required"/>
        <xs:attribute name="sortOrder" type="xs:integer" use="optional"/>
    </xs:complexType>

    <xs:complexType name="fieldDeclaration">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="label" type="xs:string" use="required"/>
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="required" type="xs:boolean" use="optional"/>
        <xs:attribute name="notice" type="xs:string" use="optional"/>
        <xs:attribute name="value" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:simpleType name="modelName">
        <xs:annotation>
            <xs:documentation>
                Model name can contain only [a-zA-Z_\\\\].
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z_\\\\]+" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== firebearstudio/importexportfree/etc/source_types.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="source_types.xsd">
    <type name="dropbox" label="Dropbox" modelInstance="Firebear\ImportExport\Model\Source\Type\Dropbox" sortOrder="10">
       <field name="file_path" id="file_path" label="File Path" type="text" required="true" />
       <!-- <field name="access_token" id="access_token" label="Access Token" type="text" required="true" />-->
        <field name="images_on_dropbox" id="images_on_dropbox" label="Import Images From Dropbox" type="checkbox" value="1"/>
        <field name="import_images_file_dir" id="file_import_images_file_dir" label="Images File Directory" type="text" notice="Use relative path to Magento installation, e.g. var/import/images/"/>
    </type>
    <type name="ftp" label="Ftp" modelInstance="Firebear\ImportExport\Model\Source\Type\Ftp" sortOrder="20">
        <field name="file_path" id="file_path" label="File Path" type="text" required="true" />
        <field name="host" id="host" label="Host" type="text" required="true" />
        <field name="port" id="port" label="Port" type="text" required="true" />
        <field name="user" id="username" label="Username" type="text" required="true" />
        <field name="password" id="password" label="Password" type="text" required="true" />
    </type>
    <type name="url" label="Url" modelInstance="Firebear\ImportExport\Model\Source\Type\Url" sortOrder="30">
        <field name="file_path" id="file_path" label="Url" type="text" required="true" />
    </type>

</config>
